/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Stan
 */
public class welcome extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement stmt = null;
    
    String url = "jdbc:mysql://localhost:3306/sms";
    String un = "root";
    String pas = "root";
    
    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        lib = new javax.swing.JMenuItem();
        lecturers = new javax.swing.JMenuItem();
        stud_infor = new javax.swing.JMenuItem();
        portal = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(700, 500));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(568, 400));
        setPreferredSize(new java.awt.Dimension(250, 250));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SCHOOL MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 0, 255));
        jLabel2.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentY(0.0F);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 300, 70));

        jButton6.setText("Contact Us");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, 40));

        jButton7.setText("Apply");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 80, 40));

        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, 40));

        jMenu1.setText("INSTITUTION");

        lib.setText("LIBRARY");
        lib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libActionPerformed(evt);
            }
        });
        jMenu1.add(lib);

        lecturers.setText("LECTURERS");
        lecturers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturersMouseClicked(evt);
            }
        });
        lecturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturersActionPerformed(evt);
            }
        });
        jMenu1.add(lecturers);

        stud_infor.setText("STUDENT INFORMATION");
        stud_infor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stud_inforMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stud_inforMousePressed(evt);
            }
        });
        stud_infor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_inforActionPerformed(evt);
            }
        });
        jMenu1.add(stud_infor);

        jMenuBar1.add(jMenu1);

        portal.setText("STUDENT PORTAL");
        portal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        portal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                portalMouseClicked(evt);
            }
        });
        portal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portalActionPerformed(evt);
            }
        });
        jMenuBar1.add(portal);

        jMenu5.setText("E-LEARNING");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void portalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portalActionPerformed
        // TODO add your handling code here:
        studentPortal obj = new studentPortal();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_portalActionPerformed

    private void portalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_portalMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_portalMouseClicked

    private void libActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libActionPerformed

    private void stud_inforMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stud_inforMousePressed
        try {
            // TODO add your handling code here:
            
//        String url = "jdbc:mysql://localhost:3306/sms";
//        String un = "root";
//        String pas = "root";

        conn =DriverManager.getConnection(url, un, pas);
        studentDetails details = new studentDetails();
        details.setVisible(true);
        dispose();
        } catch (SQLException ex) {
            Logger.getLogger(welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_stud_inforMousePressed

    private void stud_inforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_inforActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_stud_inforActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void stud_inforMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stud_inforMouseClicked
        // TODO add your handling code here:
        staff_login studDetails = new staff_login();
        studDetails.setVisible(true);
        dispose();
    }//GEN-LAST:event_stud_inforMouseClicked

    private void lecturersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturersMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        application app = new application();
        app.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void lecturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturersActionPerformed
        // TODO add your handling code here:
        staff_login obj = new staff_login();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_lecturersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem lecturers;
    private javax.swing.JMenuItem lib;
    private javax.swing.JButton login;
    private javax.swing.JMenu portal;
    private javax.swing.JMenuItem stud_infor;
    // End of variables declaration//GEN-END:variables
}
